management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    application:
      name: pichincha-api
      description: A challenge pichincha spring api
      author: YesithV
      version: 1.0

spring:
  profiles:
    active: dev
  application:
    name: pichincha-api
    
server:
  port: 8001

